export const UserTypes = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",

  ADD_USER: "ADD_USER",

  GET_All_USER: "GET_All_USER",
  GET_USER_BY_ID: "GET_USER_BY_ID",
  GET_USER_BY_FILTER: "GET_USER_BY_FILTER",

  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  ADD_USER_FAIL: "ADD_USER_FAIL",

  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_BY_ID_SUCCESS: "GET_USER_BY_ID_SUCCESS",

  SET_LOADING: "SET_LOADING",
};

export const ProductTypes = {
  GET_All_PRODUCT: "GET_All_PRODUCT",
  GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID",
  GET_PRODUCT_BY_FILTER: "GET_PRODUCT_BY_FILTER",

  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",

  SET_LOADING: "SET_LOADING",
};

export const BrandTypes = {
  GET_All_BRAND: "GET_All_BRAND",
  GET_BRAND_BY_ID: "GET_BRAND_BY_ID",

  GET_BRAND_SUCCESS: "GET_BRAND_SUCCESS",
  GET_BRAND_BY_ID_SUCCESS: "GET_BRAND_BY_ID_SUCCESS",

  SET_LOADING: "SET_LOADING",
};

export const OrderTypes = {
  GET_All_ORDER: "GET_All_ORDER",
  GET_ORDER_BY_FILTER: "GET_ORDER_BY_FILTER",
  GET_ORDER_BY_ID: "GET_ORDER_BY_ID",

  GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
  GET_ORDER_BY_ID_SUCCESS: "GET_ORDER_BY_ID_SUCCESS",

  SET_LOADING: "SET_LOADING",
};

export const CartTypes = {
  GET_CART: "GET_CART",
  ADD_CART: "ADD_CART",
  REMOVE_CART: "REMOVE_CART",
  CLEAR_CART: "CLEAR_CART",
};

export const Status = {
  PROCESSING: "PROCESSING",
  SHIPPING: "SHIPPING",
  DELIVERED: "DELIVERED",
  CANCELED: "CANCELED",
};

export const PaymentTypes = {
  VISA: "visa",
  PAYPAL: "paypal",
  CASH: "cash",
};
