export const UserTypes = {
  ADD_USER: "ADD_USER",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",

  DELETE_USER: "DELETE_USER",
  GET_All_USER: "GET_All_USER",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_BY_ID: "GET_USER_BY_ID",
  GET_USER_BY_ID_SUCCESS: "GET_USER_BY_ID_SUCCESS",
  SET_LOADING: "SET_LOADING",
};
